"""Add CheckConstraint for Shows

Revision ID: 0f50b2a0eb65
Revises: b7a54856636b
Create Date: 2026-09-04 20:56:11.726587

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0f50b2a0eb65'
down_revision: str | Sequence[str] | None = 'b7a54856636b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'section',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_check_constraint('check_published_show_has_section', 'shows', "(status = 'draft') OR (section IS NOT NULL)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_published_show_has_section', 'shows', type_='check')
    op.alter_column('shows', 'section',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
